project_id = "dybbailvbaaovkstgpoh"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.ai-financial-coach]
verify_jwt = true

[functions.narrative-engine]
verify_jwt = false

[functions.update-exchange-rates]
verify_jwt = false

[functions.admin-send-email]
verify_jwt = true

[functions.provision-categories]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.data-integrity-check]
verify_jwt = false

[functions.generate-blog-article]
verify_jwt = false
