project_id = "dybbailvbaaovkstgpoh"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.ai-financial-coach]
verify_jwt = false

[functions.narrative-engine]
verify_jwt = false

[functions.update-exchange-rates]
verify_jwt = false